import { useEffect, useMemo, useState } from 'react'
import { ArrowDownLeft, Check, CircleHelp, Clock3, CreditCard, Search, Wallet } from 'lucide-react'
import { api } from '../lib/services'
import { isSupabaseConfigured } from '../lib/supabase'
import { formatDate, money, errorMessage, newIdempotencyKey } from '../lib/utils'
import type { Customer } from '../lib/types'
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, EmptyState, Input, Label, LoadingState, Select, useToast } from '../components/ui'

export function CollectionsPage({initialCustomerId}:{initialCustomerId?:string}){
 const{toast}=useToast();const[customers,setCustomers]=useState<Customer[]>([]);const[selected,setSelected]=useState(initialCustomerId||'');const[search,setSearch]=useState('');const[sales,setSales]=useState<any[]>([]);const[payments,setPayments]=useState<any[]>([]);const[amount,setAmount]=useState('');const[method,setMethod]=useState('cash');const[reference,setReference]=useState('');const[invoiceId,setInvoiceId]=useState('');const[loading,setLoading]=useState(true);const[loadingInvoices,setLoadingInvoices]=useState(false);const[saving,setSaving]=useState(false)
 async function loadCustomers(){setLoading(true);if(!isSupabaseConfigured){setCustomers([]);setLoading(false);return}try{const rows=await api.customers();setCustomers(rows as Customer[])}catch(e){toast('Customers could not load',errorMessage(e),'error')}finally{setLoading(false)}}
 useEffect(()=>{void loadCustomers()},[])
 useEffect(()=>{if(initialCustomerId)setSelected(initialCustomerId)},[initialCustomerId])
 useEffect(()=>{async function loadInvoices(){if(!selected||!isSupabaseConfigured){setSales([]);return}setLoadingInvoices(true);try{const [allSales,allPays]=await Promise.all([api.customerSales(selected),api.customerPayments(selected)]);setSales(allSales.filter(s=>s.status==='posted'&&Number(s.balance_due)>0));setPayments(allPays.filter(p=>p.direction==='in'))}catch(e){toast('Customer balance could not load',errorMessage(e),'error')}finally{setLoadingInvoices(false)}}void loadInvoices()},[selected])
 const due=Number(customers.find(c=>c.id===selected)?.outstanding_balance||0);const filteredCustomers=useMemo(()=>customers.filter(c=>c.name.toLowerCase().includes(search.toLowerCase())||(c.mobile||'').includes(search)).filter(c=>Number(c.outstanding_balance)>0),[customers,search]);const chosenSale=sales.find(s=>s.id===invoiceId)
 async function submit(e:React.FormEvent){e.preventDefault();const amt=Math.round(Number(amount)*100)/100;if(!selected||amt<=0){toast('Check payment details','Select a customer and enter a positive amount.','error');return}if(amt>due+.009){toast('Amount exceeds outstanding',`Current balance is ${money(due)}.`,'error');return}if(chosenSale&&amt>Number(chosenSale.balance_due)+.009){toast('Amount exceeds invoice balance',`Selected invoice has ${money(chosenSale.balance_due)} pending. Clear invoice selection to allocate FIFO across open bills.`,'error');return}setSaving(true);try{const payload:any={customer_id:selected,amount:amt,method,reference:reference.trim()||null,idempotency_key:newIdempotencyKey()};if(invoiceId)payload.allocations=[{sale_id:invoiceId,amount:amt}];const result=await api.receiveCustomerPayment(payload);toast(result.duplicate?'Payment already recorded':'Payment received',`${money(amt)} recorded and allocated ${invoiceId?'to the selected invoice':'oldest open invoice first'}.`);setAmount('');setReference('');setInvoiceId('');await Promise.all([loadCustomers(),refreshInvoices()])}catch(e){toast('Payment not recorded',errorMessage(e),'error')}finally{setSaving(false)}}
 async function refreshInvoices(){if(!selected||!isSupabaseConfigured)return;const[a,p]=await Promise.all([api.customerSales(selected),api.customerPayments(selected)]);setSales(a.filter(s=>s.status==='posted'&&Number(s.balance_due)>0));setPayments(p.filter(x=>x.direction==='in'))}
 const selectedCustomer=customers.find(c=>c.id===selected)
 return <div className="space-y-5"><div><div className="eyebrow">Customer receipts · invoice allocation</div><h1 className="mt-1.5 text-[26px] font-bold tracking-tight text-slate-900 dark:text-white">Receive payment</h1><p className="mt-1 text-sm text-slate-500">Record cash, UPI or bank collection against one or more Udhar invoices.</p></div>
 {!isSupabaseConfigured&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">Live payment recording is disabled until Supabase is configured. This preview contains no customer names or balances.</div>}
 <div className="grid items-start gap-5 xl:grid-cols-[.9fr_1.1fr]"><Card><CardHeader><div><CardTitle>Customers with due balances</CardTitle><p className="mt-1 text-xs text-slate-400">Choose a customer before recording a receipt.</p></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-700"><ArrowDownLeft size={18}/></div></CardHeader><CardContent className="space-y-3"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customer / mobile" className="pl-9"/></div>{loading?<LoadingState/>:filteredCustomers.length?<div className="max-h-[420px] space-y-2 overflow-auto">{filteredCustomers.map(c=><button key={c.id} onClick={()=>{setSelected(c.id);setInvoiceId('');setAmount('')}} className={`flex w-full items-center justify-between gap-2 rounded-xl border p-3 text-left transition ${selected===c.id?'border-brand-300 bg-brand-50 dark:border-brand-700 dark:bg-brand-900/25':'border-slate-100 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-800/60'}`}><div className="min-w-0"><div className="truncate text-xs font-semibold text-slate-800 dark:text-slate-100">{c.name}</div><div className="mt-1 text-[10px] text-slate-400">{c.mobile||'No mobile'}{c.village?` · ${c.village}`:''}</div></div><div className="text-right"><div className="text-xs font-bold text-amber-700">{money(c.outstanding_balance)}</div><div className="text-[9px] text-slate-400">outstanding</div></div></button>)}</div>:<EmptyState title="No outstanding balances" description="Credit sales with a pending amount appear here." icon={<Wallet size={28}/>} />}</CardContent></Card>
 <div className="space-y-4"><Card><CardHeader><div><CardTitle>Record collection</CardTitle><p className="mt-1 text-xs text-slate-400">Customer due is updated atomically when saved.</p></div></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><div><Label>Customer</Label><Select value={selected} onChange={e=>{setSelected(e.target.value);setInvoiceId('');setAmount('')}}><option value="">Select customer…</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name} · Due {money(c.outstanding_balance)}</option>)}</Select></div>{selectedCustomer&&<div className="flex items-center justify-between rounded-xl bg-amber-50 px-4 py-3 dark:bg-amber-900/20"><div><div className="text-[10px] font-semibold uppercase tracking-wide text-amber-700">Current outstanding</div><div className="mt-1 text-lg font-bold text-amber-900 dark:text-amber-200">{money(due)}</div></div><Badge tone="amber">{sales.length} open invoice{sales.length===1?'':'s'}</Badge></div>}
 <div className="grid grid-cols-2 gap-3"><div><Label>Received amount (₹)</Label><Input autoFocus type="number" min="0.01" max={due} step="0.01" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00" required/></div><div><Label>Method</Label><Select value={method} onChange={e=>setMethod(e.target.value)}><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="other">Other</option></Select></div></div><div><Label>Allocate to invoice <span className="font-normal text-slate-400">(optional; default FIFO)</span></Label><Select value={invoiceId} onChange={e=>setInvoiceId(e.target.value)}><option value="">Oldest open invoice first</option>{sales.map(s=><option key={s.id} value={s.id}>{s.invoice_number} · {formatDate(s.sold_at)} · Due {money(s.balance_due)}</option>)}</Select></div>{method==='upi'&&<div><Label>UPI reference / UTR</Label><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Transaction ID (optional)"/></div>}{method!=='upi'&&<div><Label>Reference / note</Label><Input value={reference} onChange={e=>setReference(e.target.value)} placeholder="Receipt number or note (optional)"/></div>}
 {selectedCustomer?.credit_limit&&Number(selectedCustomer.credit_limit)>0&&<div className="text-[10px] text-slate-400">Credit limit {money(selectedCustomer.credit_limit)} · receipt cannot exceed current outstanding.</div>}
 <Button size="lg" className="w-full" disabled={!isSupabaseConfigured||saving||!selected||due<=0}>{saving?'Recording…':<><Check size={16}/>Record payment</>}</Button></form></CardContent></Card>
 <Card><CardHeader><div><CardTitle>Recent customer receipts</CardTitle><p className="mt-1 text-xs text-slate-400">Payment history for the selected customer</p></div><Clock3 size={17} className="text-slate-400"/></CardHeader><CardContent className="pt-1">{!selected?<EmptyState title="Select a customer" description="Their latest recorded receipts will appear here."/>:loadingInvoices?<LoadingState/>:payments.length?<div className="divide-y divide-slate-100 dark:divide-slate-800">{payments.slice(0,8).map(p=><div key={p.id} className="flex items-center justify-between py-3"><div><div className="text-xs font-semibold text-slate-700 dark:text-slate-200">{money(p.amount)} · <span className="capitalize">{p.method}</span></div><div className="mt-1 text-[10px] text-slate-400">{formatDate(p.created_at)}{p.reference?` · ${p.reference}`:''}</div></div><Badge tone="green">Received</Badge></div>)}</div>:<EmptyState title="No receipts yet" description="Payments received from this customer will be saved here."/>}</CardContent></Card></div></div>
 </div>
}
