import { useEffect, useMemo, useState } from 'react'
import { ArrowDownRight, ArrowUpRight, Banknote, CalendarDays, Check, Plus, ReceiptText, Wallet } from 'lucide-react'
import { api } from '../lib/services'
import { isSupabaseConfigured } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { errorMessage, formatDate, localDateISO, money } from '../lib/utils'
import { Badge, Button, Card, CardContent, CardHeader, CardTitle, Dialog, DialogHeader, EmptyState, Input, Label, LoadingState, Select, useToast } from '../components/ui'

const categories=['Rent','Electricity','Salary','Transport','Loading / Unloading','Repairs','Miscellaneous']
export function ExpensesPage(){const{profile}=useAuth();const{toast}=useToast();const[date,setDate]=useState(localDateISO());const[expenses,setExpenses]=useState<any[]>([]);const[cashbook,setCashbook]=useState<any>(null);const[loading,setLoading]=useState(true);const[dialog,setDialog]=useState(false);const[closeOpen,setCloseOpen]=useState(false);const[form,setForm]=useState<any>({category:'Rent',description:'',amount:'',method:'cash',reference:'',spent_at:localDateISO()});const[counted,setCounted]=useState('');const[closingNote,setClosingNote]=useState('');const[saving,setSaving]=useState(false);const[closingBusy,setClosingBusy]=useState(false);const canManage=profile?.role_code==='owner'||profile?.role_code==='manager'
 async function load(){setLoading(true);if(!isSupabaseConfigured){setExpenses([]);setCashbook(null);setLoading(false);return}try{const[e,c]=await Promise.all([api.expenses(date,date),api.cashSnapshot(date)]);setExpenses(e);setCashbook(c);setCounted(c.counted_closing===null||c.counted_closing===undefined?'':String(c.counted_closing))}catch(e){toast('Cashbook could not load',errorMessage(e),'error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[date])
 const expected=Number(cashbook?.expected_closing||0);const difference=cashbook?.difference===null||cashbook?.difference===undefined?null:Number(cashbook.difference);const expenseTotal=expenses.reduce((s,e)=>s+Number(e.amount||0),0);const upiNet=Number(cashbook?.upi_in||0)-Number(cashbook?.upi_out||0)
 async function addExpense(e:React.FormEvent){e.preventDefault();setSaving(true);try{await api.expense({...form,amount:Number(form.amount),spent_at:date});toast('Expense recorded',`${money(form.amount)} saved under ${form.category}.`);setDialog(false);setForm({category:'Rent',description:'',amount:'',method:'cash',reference:'',spent_at:date});await load()}catch(e){toast('Expense was not saved',errorMessage(e),'error')}finally{setSaving(false)}}
 async function saveClosing(e:React.FormEvent){e.preventDefault();if(Number(counted)<0){toast('Invalid counted cash','Count must be zero or more.','error');return}setClosingBusy(true);try{const row=await api.saveCashClosing({closing_date:date,counted_cash:Number(counted),note:closingNote||null});toast('Cash closing saved',`Difference: ${money(row.difference)}.`);setCloseOpen(false);await load()}catch(e){toast('Cash closing was not saved',errorMessage(e),'error')}finally{setClosingBusy(false)}}
 const metrics=[['Opening cash',cashbook?.opening_cash,'green'],['Cash sales',cashbook?.cash_sales,'green'],['Cash collections',cashbook?.cash_collections,'blue'],['Cash purchases',cashbook?.cash_purchases,'amber'],['Supplier payments',cashbook?.cash_supplier_payments,'amber'],['Cash refunds',cashbook?.cash_refunds,'rose'],['Cash expenses',cashbook?.cash_expenses,'rose'],['UPI net (separate)',upiNet,'blue']]
 return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="eyebrow">Daily expenses · physical cash reconciliation</div><h1 className="mt-1.5 text-[26px] font-bold tracking-tight text-slate-900 dark:text-white">Expenses & cashbook</h1><p className="mt-1 text-sm text-slate-500">Physical cash is reconciled separately from UPI and bank transactions.</p></div><div className="flex flex-wrap gap-2"><div className="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 dark:border-slate-700 dark:bg-slate-900"><CalendarDays size={15} className="text-slate-400"/><Input aria-label="Cashbook date" type="date" value={date} onChange={e=>setDate(e.target.value)} className="h-10 w-[145px] border-0 bg-transparent px-0 focus:ring-0"/></div><Button variant="outline" onClick={()=>setDialog(true)} disabled={!canManage||!isSupabaseConfigured}><Plus size={15}/>Record expense</Button><Button onClick={()=>setCloseOpen(true)} disabled={!canManage||!isSupabaseConfigured}><Banknote size={15}/>Count closing cash</Button></div></div>
 {!isSupabaseConfigured&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">No cash or expense amounts are fabricated. Configure Supabase to use live ledgers.</div>}
 {loading?<Card><LoadingState label="Calculating cashbook…"/></Card>:<><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label,value,tone])=><Tile key={String(label)} label={String(label)} value={isSupabaseConfigured?money(value as any):'—'} tone={String(tone)}/>)}</div><div className="grid gap-4 xl:grid-cols-[1.05fr_.95fr]"><Card><CardHeader><div><CardTitle>Expected cash closing</CardTitle><p className="mt-1 text-xs text-slate-400">Opening + cash receipts + supplier refunds − payments − expenses</p></div><div className="grid h-9 w-9 place-items-center rounded-xl bg-brand-50 text-brand-700"><Wallet size={18}/></div></CardHeader><CardContent><div className="flex flex-wrap items-end justify-between gap-3"><div><div className="eyebrow">{formatDate(date)}</div><div className="mt-2 text-3xl font-bold tracking-tight text-slate-900 dark:text-white">{isSupabaseConfigured?money(expected):'—'}</div></div><div className="text-right"><div className="eyebrow">Physically counted</div><div className="mt-2 text-xl font-bold text-slate-700 dark:text-slate-200">{cashbook?.counted_closing!=null?money(cashbook.counted_closing):'Not counted'}</div></div></div><div className={`mt-5 flex items-center justify-between rounded-xl p-3 ${difference===null?'bg-slate-50 text-slate-500 dark:bg-slate-800':Math.abs(difference)<.01?'bg-emerald-50 text-emerald-800':'bg-rose-50 text-rose-800'}`}><div className="flex items-center gap-2 text-xs font-semibold">{difference===null?<ReceiptText size={16}/>:difference>=0?<ArrowUpRight size={16}/>:<ArrowDownRight size={16}/>}Difference {difference===null?'(awaiting physical count)':difference>0?'(cash surplus)':difference<0?'(cash short)':'(matched)'}</div><div className="text-sm font-bold">{difference===null?'—':money(difference)}</div></div><Button variant="outline" className="mt-4 w-full" onClick={()=>setCloseOpen(true)} disabled={!canManage}><Banknote size={15}/>{cashbook?.counted_closing!=null?'Update physical count':'Enter physical closing cash'}</Button></CardContent></Card>
 <Card><CardHeader><div><CardTitle>Formula breakdown</CardTitle><p className="mt-1 text-xs text-slate-400">UPI receipts are intentionally excluded from physical cash.</p></div><Badge tone="blue">{formatDate(date,{day:'2-digit',month:'short'})}</Badge></CardHeader><CardContent className="space-y-2">{[['Opening cash',cashbook?.opening_cash,'+'],['Cash sales',cashbook?.cash_sales,'+'],['Customer collections',cashbook?.cash_collections,'+'],['Supplier refunds received',cashbook?.supplier_refunds,'+'],['Cash purchases',cashbook?.cash_purchases,'−'],['Supplier payments',cashbook?.cash_supplier_payments,'−'],['Sales refunds',cashbook?.cash_refunds,'−'],['Cash expenses',cashbook?.cash_expenses,'−']].map(([label,value,sign])=><div key={String(label)} className="flex items-center justify-between border-b border-slate-50 py-2 text-xs last:border-0 dark:border-slate-800"><span className="text-slate-500">{label}</span><span className="font-semibold text-slate-700 dark:text-slate-200">{sign==='−'?'− ':''}{isSupabaseConfigured?money(value as any):'—'}</span></div>)}<div className="mt-2 flex justify-between border-t border-slate-200 pt-3 text-sm font-bold dark:border-slate-700"><span>Expected cash</span><span>{isSupabaseConfigured?money(expected):'—'}</span></div></CardContent></Card></div>
 <Card><CardHeader><div><CardTitle>Expenses on {formatDate(date)}</CardTitle><p className="mt-1 text-xs text-slate-400">Recorded operating expenses · {expenses.length} entries · {money(expenseTotal)}</p></div></CardHeader><CardContent className="pt-1">{expenses.length?<div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="bg-slate-50 text-slate-400 dark:bg-slate-900"><tr className="text-[10px] uppercase tracking-wide"><th className="px-4 py-2.5">Category / description</th><th className="px-2 py-2.5">Method</th><th className="px-2 py-2.5">Reference</th><th className="px-4 py-2.5 text-right">Amount</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-4 py-3"><div className="text-xs font-semibold">{x.description}</div><div className="mt-1 text-[10px] text-slate-400">{x.category}</div></td><td className="px-2 py-3 text-xs capitalize">{x.method}</td><td className="px-2 py-3 text-xs text-slate-400">{x.reference||'—'}</td><td className="px-4 py-3 text-right text-xs font-semibold">{money(x.amount)}</td></tr>)}</tbody></table></div>:<EmptyState title={isSupabaseConfigured?'No expenses on this day':'No connected expense records'} description={isSupabaseConfigured?'Use Record expense to add shop operating costs.':'Actual expenses will appear after you connect Supabase.'} icon={<ReceiptText size={28}/>} />}</CardContent></Card></>}
 <Dialog open={dialog} onOpenChange={setDialog}><DialogHeader title="Record an expense" description="The expense is included in net profit and cashbook by payment method."/><form onSubmit={addExpense} className="space-y-4 p-6"><div className="grid grid-cols-2 gap-3"><div><Label>Category</Label><Select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{categories.map(c=><option key={c}>{c}</option>)}</Select></div><div><Label>Date</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)}/></div></div><div><Label>Description *</Label><Input autoFocus value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="e.g. October shop rent" required/></div><div className="grid grid-cols-2 gap-3"><div><Label>Amount (₹) *</Label><Input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} required/></div><div><Label>Payment method</Label><Select value={form.method} onChange={e=>setForm({...form,method:e.target.value})}><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="other">Other</option></Select></div></div><div><Label>Reference / note</Label><Input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setDialog(false)}>Cancel</Button><Button disabled={saving||!isSupabaseConfigured||!canManage}>{saving?'Saving…':'Save expense'}</Button></div></form></Dialog>
 <Dialog open={closeOpen} onOpenChange={setCloseOpen}><DialogHeader title="Count physical closing cash" description={`Expected cash for ${formatDate(date)} is ${money(expected)}. Enter the amount physically counted.`}/><form onSubmit={saveClosing} className="space-y-4 p-6"><div><Label>Counted cash (₹) *</Label><Input autoFocus type="number" min="0" step="0.01" value={counted} onChange={e=>setCounted(e.target.value)} placeholder="0.00" required/></div><div><Label>Reconciliation note</Label><Input value={closingNote} onChange={e=>setClosingNote(e.target.value)} placeholder="Optional note for any difference"/></div><div className="rounded-xl bg-slate-50 p-3 text-xs dark:bg-slate-800"><div className="flex justify-between text-slate-500"><span>Expected</span><span>{money(expected)}</span></div><div className="mt-1 flex justify-between font-semibold"><span>Difference</span><span>{counted?money(Number(counted)-expected):'—'}</span></div></div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setCloseOpen(false)}>Cancel</Button><Button disabled={closingBusy||!canManage}>{closingBusy?'Saving…':<><Check size={15}/>Save closing</>}</Button></div></form></Dialog>
 </div>}
function Tile({label,value,tone}:{label:string;value:string;tone:string}){const c:any={green:'bg-brand-50 text-brand-700',blue:'bg-blue-50 text-blue-700',amber:'bg-amber-50 text-amber-700',rose:'bg-rose-50 text-rose-700'};return <Card className="p-4"><div className="eyebrow">{label}</div><div className="mt-2 text-lg font-bold text-slate-900 dark:text-white">{value}</div><div className={`mt-2 grid h-7 w-7 place-items-center rounded-lg ${c[tone]}`}><Wallet size={14}/></div></Card>}
