import { useEffect, useMemo, useState } from 'react'
import { ArrowDownToLine, Ban, CalendarDays, FileText, Printer, Search } from 'lucide-react'
import { api } from '../lib/services'
import { isSupabaseConfigured } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import { downloadCsv, errorMessage, formatDate, money, localDateISO } from '../lib/utils'
import type { InvoiceData } from '../components/Invoice'
import { InvoicePreview } from '../components/Invoice'
import { Badge, Button, Card, Dialog, DialogHeader, EmptyState, Input, LoadingState, Select, useToast } from '../components/ui'

export function SalesHistoryPage(){const{profile}=useAuth();const{toast}=useToast();const[rows,setRows]=useState<any[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[period,setPeriod]=useState('30d');const[customFrom,setCustomFrom]=useState(localDateISO());const[customTo,setCustomTo]=useState(localDateISO());const[detail,setDetail]=useState<any|null>(null);const[paymentRows,setPaymentRows]=useState<any[]>([]);const[detailLoading,setDetailLoading]=useState(false);const[reverseBusy,setReverseBusy]=useState(false);const[invoiceMode,setInvoiceMode]=useState<'a4'|'thermal'>('a4');const canReverse=profile?.role_code==='owner'||profile?.role_code==='manager'
 const dateRange=useMemo(()=>{const end=new Date();const start=new Date(end);if(period==='today')start.setDate(start.getDate());else if(period==='7d')start.setDate(start.getDate()-6);else if(period==='30d')start.setDate(start.getDate()-29);else if(period==='month')start.setDate(1);else return{from:customFrom,to:customTo};return{from:localDateISO(start),to:localDateISO(end)}},[period,customFrom,customTo])
 async function load(){setLoading(true);if(!isSupabaseConfigured){setRows([]);setLoading(false);return}try{setRows(await api.sales(dateRange.from,dateRange.to))}catch(e){toast('Sales history could not load',errorMessage(e),'error')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[dateRange.from,dateRange.to])
 const shown=rows.filter(s=>`${s.invoice_number} ${s.customers?.name||s.historical_customer_name||''} ${s.customers?.mobile||''}`.toLowerCase().includes(search.toLowerCase()))
 async function openInvoice(s:any){setDetail(s);setDetailLoading(true);try{setPaymentRows(await api.salePayments(s.id))}catch(e){toast('Payment details unavailable',errorMessage(e),'error')}finally{setDetailLoading(false)}}
 async function reverseSale(){if(!detail)return;if(!window.confirm(`Reverse the entire sale ${detail.invoice_number}? Stock will be returned and any paid amount will be recorded as a cash refund. This cannot be undone.`))return;setReverseBusy(true);try{await api.reverseSale(detail.id,'cash');toast('Invoice reversed',`${detail.invoice_number} was reversed with stock and ledger entries.`);setDetail(null);await load()}catch(e){toast('Sale reversal failed',errorMessage(e),'error')}finally{setReverseBusy(false)}}
 function exportRows(){downloadCsv('banke-vihari-sales.csv',shown.map(s=>({Invoice:s.invoice_number,Date:formatDate(s.sold_at),Customer:s.customers?.name||s.historical_customer_name||'Walk-in',Subtotal:Number(s.taxable_amount),GST:Number(s.gst_amount),Total:Number(s.total),Paid:Number(s.amount_paid),Due:Number(s.balance_due),Status:s.status,PaymentStatus:s.payment_status,Origin:s.origin}))) }
 const selectedPayments=paymentRows.map(p=>p.payments?.method).filter(Boolean) as string[]
 const invoice:InvoiceData|undefined=detail?{invoice_number:detail.invoice_number,sold_at:detail.sold_at,customer:detail.customers?{name:detail.customers.name,mobile:detail.customers.mobile}:detail.historical_customer_name?{name:detail.historical_customer_name}:null,items:(detail.sale_items||[]).map((i:any)=>({product_name:i.product_name,quantity:Number(i.quantity),unit:i.unit,unit_price:Number(i.unit_price),discount:Number(i.discount),gst_rate:Number(i.gst_rate),gst_amount:Number(i.gst_amount),line_total:Number(i.line_total)})),subtotal:Number(detail.subtotal),discount_total:Number(detail.discount_total),gst_amount:Number(detail.gst_amount),total:Number(detail.total),amount_paid:Number(detail.amount_paid),balance_due:Number(detail.balance_due),payment_methods:Array.from(new Set(selectedPayments)),status:detail.status}:undefined
 return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="eyebrow">Invoices · returns · payment trail</div><h1 className="mt-1.5 text-[26px] font-bold tracking-tight text-slate-900 dark:text-white">Sales history</h1><p className="mt-1 text-sm text-slate-500">Review invoices, print customer copies or reverse a complete bill with approval.</p></div><Button variant="outline" onClick={exportRows}><ArrowDownToLine size={15}/>Export CSV</Button></div>
 {!isSupabaseConfigured&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">No demo invoices are shown. Sales history reads posted rows from your Supabase database once connected.</div>}
 <Card><div className="flex flex-col gap-3 border-b border-slate-100 p-4 dark:border-slate-800 lg:flex-row lg:items-center"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search invoice, customer or mobile…" className="pl-9"/></div><div className="flex flex-wrap items-center gap-2"><CalendarDays size={15} className="text-slate-400"/><Select value={period} onChange={e=>setPeriod(e.target.value)} className="w-[140px]"><option value="today">Today</option><option value="7d">Last 7 days</option><option value="30d">Last 30 days</option><option value="month">This month</option><option value="custom">Custom range</option></Select>{period==='custom'&&<><Input type="date" value={customFrom} onChange={e=>setCustomFrom(e.target.value)} className="w-[145px]"/><Input type="date" value={customTo} onChange={e=>setCustomTo(e.target.value)} className="w-[145px]"/></>}<Badge tone="gray">{shown.length} bills</Badge></div></div>
 {loading?<LoadingState/>:shown.length?<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left"><thead className="bg-slate-50/70 dark:bg-slate-900/40"><tr className="table-head"><th className="px-5 py-3">Invoice</th><th className="px-3 py-3">Customer</th><th className="px-3 py-3">Date</th><th className="px-3 py-3 text-right">Total</th><th className="px-3 py-3 text-right">Paid</th><th className="px-3 py-3 text-right">Due</th><th className="px-3 py-3">Status</th><th className="px-5 py-3 text-right">Invoice</th></tr></thead><tbody>{shown.map(s=><tr key={s.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-5 py-3.5"><div className="text-xs font-semibold">{s.invoice_number}</div><div className="mt-1 text-[10px] text-slate-400">{s.origin==='import'?'Historical import':'ERP sale'}</div></td><td className="px-3 py-3.5 text-xs text-slate-600 dark:text-slate-300">{s.customers?.name||s.historical_customer_name||'Walk-in Customer'}{s.customers?.mobile&&<div className="mt-1 text-[10px] text-slate-400">{s.customers.mobile}</div>}</td><td className="px-3 py-3.5 text-xs text-slate-500">{formatDate(s.sold_at,{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})}</td><td className="px-3 py-3.5 text-right text-xs font-semibold">{money(s.total)}</td><td className="px-3 py-3.5 text-right text-xs text-emerald-700">{money(s.amount_paid)}</td><td className="px-3 py-3.5 text-right text-xs text-amber-700">{money(s.balance_due)}</td><td className="px-3 py-3.5"><div className="flex flex-col items-start gap-1"><Badge tone={s.status==='reversed'?'red':s.payment_status==='paid'?'green':s.payment_status==='historical_unverified'?'blue':'amber'}>{s.status==='reversed'?'Reversed':s.payment_status==='historical_unverified'?'Historical / unverified':s.payment_status}</Badge>{s.status==='posted'&&s.balance_due>0&&<span className="text-[9px] text-amber-700">Credit / partial</span>}</div></td><td className="px-5 py-3.5 text-right"><Button size="sm" variant="outline" onClick={()=>void openInvoice(s)}><FileText size={14}/>View / print</Button></td></tr>)}</tbody></table></div>:<EmptyState title={search?'No invoice matches':'No sales in this period'} description={isSupabaseConfigured?'Adjust the date filter or create the first sale from POS.':'Connect the live database to see actual invoices.'} icon={<FileText size={29}/>} />}</Card>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogHeader title={detail?.invoice_number||'Invoice'} description="Review, print or export the invoice as a PDF using your browser print dialog."/><div className="p-5 sm:p-6">{detailLoading?<LoadingState/>:invoice&&<><div className="no-print mb-4 flex flex-wrap justify-between gap-2"><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setInvoiceMode('a4')}>A4</Button><Button size="sm" variant="outline" onClick={()=>setInvoiceMode('thermal')}>Thermal</Button></div>{detail?.status==='posted'&&detail?.inventory_applied&&canReverse&&<Button size="sm" variant="danger" disabled={reverseBusy} onClick={()=>void reverseSale()}><Ban size={14}/>{reverseBusy?'Reversing…':'Full bill reversal'}</Button>}</div><InvoicePreview invoice={{...invoice,payment_methods:Array.from(new Set(selectedPayments))}} mode={invoiceMode} business={profile?.business}/></>}</div></Dialog>
 </div>
}
