import { useEffect, useState } from 'react'
import { ArrowDownToLine, BookOpen, CreditCard, Plus, Search, Truck, Wallet } from 'lucide-react'
import { api } from '../lib/services'
import { isSupabaseConfigured } from '../lib/supabase'
import { useAuth } from '../lib/auth'
import type { Supplier } from '../lib/types'
import { downloadCsv, errorMessage, formatDate, money, newIdempotencyKey } from '../lib/utils'
import { Badge, Button, Card, Dialog, DialogHeader, EmptyState, Input, Label, LoadingState, Select, useToast } from '../components/ui'

const blank={name:'',contact_number:'',address:'',gstin:'',opening_balance:'0'}
export function SuppliersPage(){const{profile}=useAuth();const{toast}=useToast();const[rows,setRows]=useState<Supplier[]>([]);const[search,setSearch]=useState('');const[loading,setLoading]=useState(true);const[dialog,setDialog]=useState(false);const[editing,setEditing]=useState<Supplier|null>(null);const[form,setForm]=useState<any>({...blank});const[saving,setSaving]=useState(false);const[detail,setDetail]=useState<Supplier|null>(null);const[ledger,setLedger]=useState<any[]>([]);const[purchases,setPurchases]=useState<any[]>([]);const[payments,setPayments]=useState<any[]>([]);const[detailLoading,setDetailLoading]=useState(false);const[payOpen,setPayOpen]=useState(false);const[payAmount,setPayAmount]=useState('');const[payMethod,setPayMethod]=useState('cash');const[payReference,setPayReference]=useState('');const[paySaving,setPaySaving]=useState(false);const canManage=profile?.role_code==='owner'||profile?.role_code==='manager'
 async function load(){setLoading(true);if(!isSupabaseConfigured){setRows([]);setLoading(false);return}try{setRows(await api.suppliers(search) as Supplier[])}catch(e){toast('Suppliers could not load',errorMessage(e),'error')}finally{setLoading(false)}}
 useEffect(()=>{const t=window.setTimeout(()=>void load(),150);return()=>window.clearTimeout(t)},[search])
 function startAdd(){setEditing(null);setForm({...blank});setDialog(true)}function startEdit(s:Supplier){setEditing(s);setForm({name:s.name,contact_number:s.contact_number||'',address:s.address||'',gstin:s.gstin||'',opening_balance:'0'});setDialog(true)}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);try{const row=await api.saveSupplier({...form,id:editing?.id,opening_balance:editing?undefined:Number(form.opening_balance||0)});toast(editing?'Supplier updated':'Supplier added',`${row.name} saved.`);setDialog(false);await load()}catch(e){toast('Supplier was not saved',errorMessage(e),'error')}finally{setSaving(false)}}
 async function openDetail(s:Supplier){setDetail(s);setDetailLoading(true);try{const[l,p,pm]=await Promise.all([api.supplierLedger(s.id),api.supplierPurchases(s.id),api.supplierPayments(s.id)]);setLedger(l);setPurchases(p);setPayments(pm)}catch(e){toast('Supplier ledger could not load',errorMessage(e),'error')}finally{setDetailLoading(false)}}
 async function submitPayment(e:React.FormEvent){e.preventDefault();if(!detail)return;const value=Math.round(Number(payAmount)*100)/100;if(value<=0||value>Number(detail.outstanding_balance)+.009){toast('Check payment amount',`Amount must be positive and no more than ${money(detail.outstanding_balance)}.`,'error');return}setPaySaving(true);try{await api.receiveSupplierPayment({supplier_id:detail.id,amount:value,method:payMethod,reference:payReference.trim()||null,idempotency_key:newIdempotencyKey()});toast('Supplier payment recorded',`${money(value)} settled against oldest open purchase first.`);setPayOpen(false);setPayAmount('');setPayReference('');await load();await openDetail({...detail,outstanding_balance:Number(detail.outstanding_balance)-value})}catch(e){toast('Payment was not recorded',errorMessage(e),'error')}finally{setPaySaving(false)}}
 function exportLedger(){if(!detail)return;let bal=0;downloadCsv(`supplier-ledger-${detail.name.replace(/[^a-z0-9]+/gi,'-').toLowerCase()}.csv`,ledger.map(e=>{bal+=Number(e.credit||0)-Number(e.debit||0);return{Date:formatDate(e.txn_at),Particulars:e.description,PurchaseCredit:Number(e.credit||0),PaymentDebit:Number(e.debit||0),BalanceDue:bal}}))}
 const totalPurchases=purchases.reduce((s,p)=>s+Number(p.total||0),0);const totalPaid=payments.filter(p=>p.direction==='out').reduce((s,p)=>s+Number(p.amount||0),0)
 return <div className="space-y-5"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end"><div><div className="eyebrow">Vendors · purchase credit · settlements</div><h1 className="mt-1.5 text-[26px] font-bold tracking-tight text-slate-900 dark:text-white">Suppliers</h1><p className="mt-1 text-sm text-slate-500">Track purchase history, partial settlements and payable balances.</p></div><Button onClick={startAdd} disabled={!isSupabaseConfigured||!canManage}><Plus size={16}/>Add supplier</Button></div>
 {!isSupabaseConfigured&&<div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-800">Supplier records and balances are not seeded; connect the live database to begin.</div>}
 <div className="grid gap-3 sm:grid-cols-3"><Small label="Suppliers" value={isSupabaseConfigured?String(rows.length):'—'} icon={<Truck size={17}/>} tone="blue"/><Small label="Supplier outstanding" value={isSupabaseConfigured?money(rows.reduce((n,s)=>n+Number(s.outstanding_balance||0),0)):'—'} icon={<Wallet size={17}/>} tone="amber"/><Small label="With due balance" value={isSupabaseConfigured?String(rows.filter(s=>Number(s.outstanding_balance)>0).length):'—'} icon={<CreditCard size={17}/>} tone="rose"/></div>
 <Card><div className="flex items-center gap-3 border-b border-slate-100 p-4 dark:border-slate-800"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search suppliers or contact number…" className="pl-9"/></div><Badge tone="gray">{rows.length}</Badge></div>{loading?<LoadingState/>:rows.length?<div className="overflow-x-auto"><table className="w-full min-w-[730px] text-left"><thead className="bg-slate-50/70 dark:bg-slate-900/40"><tr className="table-head"><th className="px-5 py-3">Supplier</th><th className="px-3 py-3">Contact</th><th className="px-3 py-3">GSTIN</th><th className="px-3 py-3 text-right">Outstanding</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody>{rows.map(s=><tr key={s.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-5 py-3.5"><button onClick={()=>void openDetail(s)} className="text-left text-xs font-semibold text-slate-800 hover:text-brand-700 dark:text-slate-100">{s.name}</button><div className="mt-1 text-[10px] text-slate-400">{s.address||'Address not set'}</div></td><td className="px-3 py-3.5 text-xs text-slate-500">{s.contact_number||'—'}</td><td className="px-3 py-3.5 text-xs text-slate-500">{s.gstin||'—'}</td><td className="px-3 py-3.5 text-right"><Badge tone={Number(s.outstanding_balance)>0?'amber':'green'}>{money(s.outstanding_balance)}</Badge></td><td className="px-5 py-3.5"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon-sm" title="View ledger" onClick={()=>void openDetail(s)}><BookOpen size={15}/></Button><Button variant="ghost" size="icon-sm" title="Edit supplier" disabled={!canManage} onClick={()=>startEdit(s)}><Truck size={15}/></Button><Button variant="outline" size="sm" disabled={Number(s.outstanding_balance)<=0} onClick={()=>{setDetail(s);setPayOpen(true);setPayAmount(String(s.outstanding_balance))}}><Wallet size={14}/>Pay</Button></div></td></tr>)}</tbody></table></div>:<EmptyState title={isSupabaseConfigured?'No suppliers yet':'No live suppliers'} description={isSupabaseConfigured?'Add a supplier before recording a purchase.':'Connect Supabase to populate actual suppliers.'} icon={<Truck size={30}/>} />}</Card>
 <Dialog open={dialog} onOpenChange={setDialog}><DialogHeader title={editing?'Edit supplier':'Add supplier'} description="Opening balance is written once to the supplier ledger."/><form onSubmit={save} className="space-y-4 p-6"><div><Label>Supplier name *</Label><Input autoFocus required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><Label>Contact number</Label><Input inputMode="tel" value={form.contact_number} onChange={e=>setForm({...form,contact_number:e.target.value})}/></div><div><Label>GSTIN</Label><Input value={form.gstin} onChange={e=>setForm({...form,gstin:e.target.value.toUpperCase()})}/></div></div><div><Label>Address</Label><Input value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div>{!editing&&<div><Label>Opening outstanding (₹)</Label><Input type="number" min="0" step="0.01" value={form.opening_balance} onChange={e=>setForm({...form,opening_balance:e.target.value})}/></div>}<div className="flex justify-end gap-2 pt-2"><Button type="button" variant="outline" onClick={()=>setDialog(false)}>Cancel</Button><Button disabled={saving||!isSupabaseConfigured||!canManage}>{saving?'Saving…':editing?'Save changes':'Add supplier'}</Button></div></form></Dialog>
 <Dialog open={!!detail} onOpenChange={v=>!v&&setDetail(null)}><DialogHeader title={detail?.name||'Supplier ledger'} description={`${detail?.contact_number||'No contact'} · ${detail?.gstin||'No GSTIN'}`}/><div className="space-y-4 p-5">{detailLoading?<LoadingState/>:detail&&<><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Mini label="Purchases" value={money(totalPurchases)}/><Mini label="Payments made" value={money(totalPaid)}/><Mini label="Due to supplier" value={money(detail.outstanding_balance)} amber/><Mini label="Invoices" value={String(purchases.length)}/></div><div className="flex flex-wrap gap-2"><Button size="sm" disabled={Number(detail.outstanding_balance)<=0} onClick={()=>{setPayAmount(String(detail.outstanding_balance));setPayOpen(true)}}><Wallet size={14}/>Settle payable</Button><Button size="sm" variant="outline" onClick={exportLedger}><ArrowDownToLine size={14}/>Export ledger</Button><Button size="sm" variant="ghost" onClick={()=>startEdit(detail)}><Truck size={14}/>Edit</Button></div><div className="max-h-64 overflow-auto rounded-xl border border-slate-200 dark:border-slate-700"><table className="w-full min-w-[480px] text-left text-[10px]"><thead className="sticky top-0 bg-slate-50 text-slate-400 dark:bg-slate-900"><tr><th className="px-3 py-2">Date</th><th className="px-2 py-2">Particulars</th><th className="px-2 py-2 text-right">Purchase / Credit</th><th className="px-2 py-2 text-right">Paid / Debit</th></tr></thead><tbody>{ledger.map(l=><tr key={l.id} className="border-t border-slate-100 dark:border-slate-800"><td className="px-3 py-2.5 text-slate-500">{formatDate(l.txn_at)}</td><td className="px-2 py-2.5">{l.description}</td><td className="px-2 py-2.5 text-right">{Number(l.credit)?money(l.credit):'—'}</td><td className="px-2 py-2.5 text-right text-emerald-700">{Number(l.debit)?money(l.debit):'—'}</td></tr>)}</tbody></table>{!ledger.length&&<div className="py-7 text-center text-xs text-slate-400">No ledger rows.</div>}</div><div className="rounded-xl border border-slate-200 dark:border-slate-700"><div className="border-b border-slate-100 px-4 py-3 text-xs font-semibold dark:border-slate-800">Recent purchase invoices</div><div className="max-h-32 overflow-auto divide-y divide-slate-100 dark:divide-slate-800">{purchases.slice(0,8).map(p=><div key={p.id} className="flex justify-between px-4 py-2.5 text-xs"><div><div className="font-semibold">{p.purchase_number}</div><div className="text-[10px] text-slate-400">{formatDate(p.purchased_at)}</div></div><div className="text-right"><div>{money(p.total)}</div><div className="text-[10px] text-amber-700">Due {money(p.balance_due)}</div></div></div>)}</div></div></>}</div></Dialog>
 <Dialog open={payOpen} onOpenChange={setPayOpen}><DialogHeader title="Pay supplier" description={`Outstanding: ${money(detail?.outstanding_balance)}`} /><form onSubmit={submitPayment} className="space-y-4 p-6"><div><Label>Payment amount (₹)</Label><Input autoFocus type="number" min="0.01" max={detail?.outstanding_balance} step="0.01" value={payAmount} onChange={e=>setPayAmount(e.target.value)} required/></div><div><Label>Method</Label><Select value={payMethod} onChange={e=>setPayMethod(e.target.value)}><option value="cash">Cash</option><option value="upi">UPI</option><option value="bank">Bank</option><option value="other">Other</option></Select></div><div><Label>Reference / note</Label><Input value={payReference} onChange={e=>setPayReference(e.target.value)} placeholder="UTR / cheque / note"/></div><div className="rounded-xl bg-slate-50 px-3 py-2 text-[10px] text-slate-500 dark:bg-slate-800">Payment is allocated oldest unpaid purchase invoice first. This transaction cannot be duplicated by retry.</div><div className="flex justify-end gap-2"><Button type="button" variant="outline" onClick={()=>setPayOpen(false)}>Cancel</Button><Button disabled={paySaving||!isSupabaseConfigured}>{paySaving?'Saving…':'Record payment'}</Button></div></form></Dialog>
 </div>}
function Small({label,value,icon,tone}:{label:string;value:string;icon:React.ReactNode;tone:string}){const t:any={green:'bg-brand-50 text-brand-700',blue:'bg-blue-50 text-blue-700',amber:'bg-amber-50 text-amber-700',rose:'bg-rose-50 text-rose-700'};return <Card className="p-4"><div className="flex items-center justify-between"><div className="eyebrow">{label}</div><div className={`grid h-8 w-8 place-items-center rounded-xl ${t[tone]}`}>{icon}</div></div><div className="mt-2 text-xl font-bold">{value}</div></Card>}
function Mini({label,value,amber=false}:{label:string;value:string;amber?:boolean}){return <div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800/70"><div className="eyebrow">{label}</div><div className={`mt-1 text-sm font-bold ${amber?'text-amber-700':''}`}>{value}</div></div>}
